In [ ]:
import pandas as pd
df = pd.read_csv("./data/upi_transactions.csv")
df.head()

,transaction id,transaction_date,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank
0,TXN0000000001,08-10-2024 15:17,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis
1,TXN0000000002,11-04-2024 06:56,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI
2,TXN0000000003,02-04-2024 13:27,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank
3,TXN0000000004,07-01-2024 10:09,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI
4,TXN0000000005,23-01-2024 19:04,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis

In [2]:
df.shape

(250000, 10)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   transaction_date    250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
dtypes: int64(1), object(9)
memory usage: 19.1+ MB

In [4]:
df["transaction_date"] = pd.to_datetime(

    df["transaction_date"],
    format = "%d-%m-%Y %H:%M"
)

In [ ]:
df.info()

In [8]:
#Feature engineering
df["Year"] = df["transaction_date"].dt.year
df["Month"] = df["transaction_date"].dt.month
df["Day"] = df["transaction_date"].dt.day
df["Hour"] = df["transaction_date"].dt.hour
df["Minute"] = df["transaction_date"].dt.minute
df["Weekday"] = df["transaction_date"].dt.day_name()
df["Quarter"] = df["transaction_date"].dt.quarter

df.head()

,transaction id,transaction_date,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,Year,Month,Day,Hour,Minute,Weekday,Quarter
0,TXN0000000001,2024-10-08 15:17:00,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,2024,10,8,15,17,Tuesday,4
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,2024,4,11,6,56,Thursday,2
2,TXN0000000003,2024-04-02 13:27:00,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,2024,4,2,13,27,Tuesday,2
3,TXN0000000004,2024-01-07 10:09:00,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,2024,1,7,10,9,Sunday,1
4,TXN0000000005,2024-01-23 19:04:00,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,2024,1,23,19,4,Tuesday,1

In [9]:
df.iloc[0]

transaction id              TXN0000000001
transaction_date      2024-10-08 15:17:00
transaction type                      P2P
merchant_category           Entertainment
amount (INR)                          868
transaction_status                SUCCESS
sender_age_group                    26-35
receiver_age_group                  18-25
sender_state                        Delhi
sender_bank                          Axis
Year                                 2024
Month                                  10
Day                                     8
Hour                                   15
Minute                                 17
Weekday                           Tuesday
Quarter                                 4
Name: 0, dtype: object

In [10]:
df = df.set_index("transaction_date")
df.head()

,transaction id,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,Year,Month,Day,Hour,Minute,Weekday,Quarter
transaction_date,,,,,,,,,,,,,,,,
2024-10-08 15:17:00,TXN0000000001,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,2024,10,8,15,17,Tuesday,4
2024-04-11 06:56:00,TXN0000000002,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,2024,4,11,6,56,Thursday,2
2024-04-02 13:27:00,TXN0000000003,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,2024,4,2,13,27,Tuesday,2
2024-01-07 10:09:00,TXN0000000004,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,2024,1,7,10,9,Sunday,1
2024-01-23 19:04:00,TXN0000000005,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,2024,1,23,19,4,Tuesday,1

In [11]:
df.loc['2024-10-08']

,transaction id,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,Year,Month,Day,Hour,Minute,Weekday,Quarter
transaction_date,,,,,,,,,,,,,,,,
2024-10-08 15:17:00,TXN0000000001,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,2024,10,8,15,17,Tuesday,4
2024-10-08 18:12:00,TXN0000000485,P2M,Shopping,308,SUCCESS,26-35,18-25,Delhi,Yes Bank,2024,10,8,18,12,Tuesday,4
2024-10-08 16:55:00,TXN0000001116,P2M,Food,162,SUCCESS,18-25,26-35,Karnataka,ICICI,2024,10,8,16,55,Tuesday,4
2024-10-08 23:54:00,TXN0000001501,P2P,Education,17641,SUCCESS,46-55,18-25,Andhra Pradesh,Axis,2024,10,8,23,54,Tuesday,4
2024-10-08 12:11:00,TXN0000001554,Bill Payment,Grocery,276,SUCCESS,26-35,26-35,Tamil Nadu,HDFC,2024,10,8,12,11,Tuesday,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-08 23:26:00,TXN0000247470,P2P,Food,67,SUCCESS,36-45,36-45,Tamil Nadu,SBI,2024,10,8,23,26,Tuesday,4
2024-10-08 11:03:00,TXN0000247578,P2M,Fuel,573,SUCCESS,26-35,36-45,Telangana,PNB,2024,10,8,11,3,Tuesday,4
2024-10-08 17:07:00,TXN0000248029,P2P,Shopping,1714,SUCCESS,26-35,26-35,Rajasthan,PNB,2024,10,8,17,7,Tuesday,4
2024-10-08 15:58:00,TXN0000248725,P2P,Utilities,542,SUCCESS,18-25,36-45,Tamil Nadu,Axis,2024,10,8,15,58,Tuesday,4
2024-10-08 16:17:00,TXN0000249401,Bill Payment,Utilities,2846,SUCCESS,26-35,26-35,Delhi,SBI,2024,10,8,16,17,Tuesday,4