In [ ]:
import pandas as pd

dates = pd.date_range(start="2026-01-01", periods=10, freq="D")
sales_data = pd.DataFrame({"date": dates, "sales": [120, 135, None, 142, 150, 147, 160, None, 168, 180]})
sales_data

        date  sales
0 2026-01-01  120.0
1 2026-01-02  135.0
2 2026-01-03    NaN
3 2026-01-04  142.0
4 2026-01-05  150.0
5 2026-01-06  147.0
6 2026-01-07  160.0
7 2026-01-08    NaN
8 2026-01-09  168.0
9 2026-01-10  180.0

In [7]:
data_fill = sales_data.copy()
data_fill["sales"] = data_fill["sales"].ffill()
print(data_fill)

        date  sales
0 2026-01-01  120.0
1 2026-01-02  135.0
2 2026-01-03  135.0
3 2026-01-04  142.0
4 2026-01-05  150.0
5 2026-01-06  147.0
6 2026-01-07  160.0
7 2026-01-08  160.0
8 2026-01-09  168.0
9 2026-01-10  180.0

In [8]:
data_bfill = sales_data.copy()
data_bfill["sales"] = data_bfill["sales"].bfill()
print(data_bfill)

        date  sales
0 2026-01-01  120.0
1 2026-01-02  135.0
2 2026-01-03  142.0
3 2026-01-04  142.0
4 2026-01-05  150.0
5 2026-01-06  147.0
6 2026-01-07  160.0
7 2026-01-08  168.0
8 2026-01-09  168.0
9 2026-01-10  180.0

In [ ]:
data_inter = sales_data.copy()
data_inter["sales"] = data_inter["sales"].interpolate()
print(data_inter)

        date  sales
0 2026-01-01  120.0
1 2026-01-02  135.0
2 2026-01-03  138.5
3 2026-01-04  142.0
4 2026-01-05  150.0
5 2026-01-06  147.0
6 2026-01-07  160.0
7 2026-01-08  164.0
8 2026-01-09  168.0
9 2026-01-10  180.0

In [20]:
import pandas as pd

dates = pd.date_range(start="2026-01-01", periods=5, freq="D")
sales_data1 = pd.DataFrame({"date": dates, "sales": [1200, 1300, 1400, 1500, None]})
sales_data1

        date   sales
0 2026-01-01  1200.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05     NaN

In [21]:
data_inter = sales_data1.copy()
data_inter["sales"] = data_inter["sales"].interpolate(limit_direction="both")
print(data_inter)

        date   sales
0 2026-01-01  1200.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05  1500.0

In [22]:
data_inter = sales_data1.copy()
data_inter["sales"] = data_inter["sales"].interpolate(limit_direction="forward")
df = data_inter
df

        date   sales
0 2026-01-01  1200.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05  1500.0

In [23]:
data_inter1 = sales_data1.copy()
data_inter1["sales"] = data_inter1["sales"].interpolate(limit_direction="backward")
df = data_inter1
df

        date   sales
0 2026-01-01  1200.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05     NaN

In [28]:
import pandas as pd

dates = pd.date_range(start="2026-01-01", periods=5, freq="D")
sales_data1 = pd.DataFrame({"date": dates, "sales": [None, 1300, 1400, 1500, None]})
sales_data1

        date   sales
0 2026-01-01     NaN
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05     NaN

In [29]:
data_inter1 = sales_data1.copy()
data_inter1["sales"] = data_inter1["sales"].interpolate(limit_direction="backward")
df = data_inter1
df

        date   sales
0 2026-01-01  1300.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05     NaN

In [30]:
data_inter1 = sales_data1.copy()
data_inter1["sales"] = data_inter1["sales"].interpolate(limit_direction="both")
df = data_inter1
df

        date   sales
0 2026-01-01  1300.0
1 2026-01-02  1300.0
2 2026-01-03  1400.0
3 2026-01-04  1500.0
4 2026-01-05  1500.0